In [1]:
import polars as pl

# Clientes

In [2]:
clientes = pl.read_csv("../data/clientes.csv")

clientes.head()

shape: (5, 11)
┌────────────┬───────────┬─────────────┬────────┬───┬────────────┬────────────┬───────┬────────────┐
│ id_cliente ┆ nombre    ┆ apellidos   ┆ sexo   ┆ … ┆ codigo_pos ┆ fecha_alta ┆ socio ┆ tipo_clien │
│ ---        ┆ ---       ┆ ---         ┆ ---    ┆   ┆ tal        ┆ ---        ┆ ---   ┆ te         │
│ i64        ┆ str       ┆ str         ┆ str    ┆   ┆ ---        ┆ str        ┆ bool  ┆ ---        │
│            ┆           ┆             ┆        ┆   ┆ i64        ┆            ┆       ┆ str        │
╞════════════╪═══════════╪═════════════╪════════╪═══╪════════════╪════════════╪═══════╪════════════╡
│ 1          ┆ Álvaro    ┆ Castro      ┆ Mujer  ┆ … ┆ 35314      ┆ 2023-04-25 ┆ false ┆ Normal     │
│            ┆           ┆ Navarro     ┆        ┆   ┆            ┆            ┆       ┆            │
│ 2          ┆ Miguel    ┆ Martín      ┆ Mujer  ┆ … ┆ 49225      ┆ 2022-01-22 ┆ false ┆ Ocasional  │
│            ┆           ┆ Sánchez     ┆        ┆   ┆            ┆            ┆       ┆            │
│ 3          ┆ Elena     ┆ Romero      ┆ Mujer  ┆ … ┆ 23449      ┆ 2023-11-14 ┆ true  ┆ Normal     │
│            ┆           ┆ Ortega      ┆        ┆   ┆            ┆            ┆       ┆            │
│ 4          ┆ María     ┆ Romero      ┆ Hombre ┆ … ┆ 18478      ┆ 2024-06-24 ┆ true  ┆ Normal     │
│            ┆           ┆ Pérez       ┆        ┆   ┆            ┆            ┆       ┆            │
│ 5          ┆ Alejandro ┆ Jiménez     ┆ Mujer  ┆ … ┆ 36179      ┆ 2022-11-16 ┆ true  ┆ Frecuente  │
│            ┆           ┆ Castro      ┆        ┆   ┆            ┆            ┆       ┆            │
└────────────┴───────────┴─────────────┴────────┴───┴────────────┴────────────┴───────┴────────────┘

In [3]:
# Convertir la fecha a tipo Date
clientes = clientes.with_columns(
    pl.col("fecha_alta").str.to_date()
)

clientes.dtypes

[Int64,
 String,
 String,
 String,
 Int64,
 String,
 String,
 Int64,
 Date,
 Boolean,
 String]

In [4]:
# Creamos el año de alta
clientes = clientes.with_columns(
    pl.col("fecha_alta")
      .dt.year()
      .alias("anio_alta")
)

clientes.select(
    "fecha_alta",
    "anio_alta"
).head()

shape: (5, 2)
┌────────────┬───────────┐
│ fecha_alta ┆ anio_alta │
│ ---        ┆ ---       │
│ date       ┆ i32       │
╞════════════╪═══════════╡
│ 2023-04-25 ┆ 2023      │
│ 2022-01-22 ┆ 2022      │
│ 2023-11-14 ┆ 2023      │
│ 2024-06-24 ┆ 2024      │
│ 2022-11-16 ┆ 2022      │
└────────────┴───────────┘

In [5]:
# Creamos el mes de alta
clientes = clientes.with_columns(
    pl.col("fecha_alta")
      .dt.month()
      .alias("mes_alta")
)

In [ ]:
# Creamos el día de la semana
clientes = clientes.with_columns(
    pl.col("fecha_alta")
      .dt.weekday()
      .alias("dia_semana")
)

In [7]:
# Creamos diferentes grupos de edad
clientes = clientes.with_columns(

    pl.when(pl.col("edad") < 30)
      .then(pl.lit("Joven"))

    .when(pl.col("edad") < 50)
      .then(pl.lit("Adulto"))

    .when(pl.col("edad") < 65)
      .then(pl.lit("Senior"))

    .otherwise(pl.lit("Veterano"))

    .alias("grupo_edad")

)

In [8]:
# Creamos una nueva columna con la antigüedad
from datetime import date

clientes = clientes.with_columns(

    (
        date.today().year -
        pl.col("fecha_alta").dt.year()
    ).alias("antiguedad")

)

In [9]:
# Clasificamos a los clientes por antigüedad
clientes = clientes.with_columns(

    pl.when(pl.col("antiguedad") < 2)
      .then(pl.lit("Nuevo"))

    .when(pl.col("antiguedad") < 4)
      .then(pl.lit("Habitual"))

    .otherwise(pl.lit("Veterano"))

    .alias("nivel_cliente")

)

In [10]:
# Reordenamos las columnas
clientes = clientes.select(

    "id_cliente",

    "nombre",

    "apellidos",

    "sexo",

    "edad",

    "grupo_edad",

    "ciudad",

    "provincia",

    "codigo_postal",

    "fecha_alta",

    "anio_alta",

    "mes_alta",

    "dia_semana",

    "antiguedad",

    "nivel_cliente",

    "socio",

    "tipo_cliente"

)

clientes.head()

shape: (5, 17)
┌────────────┬───────────┬─────────────┬────────┬───┬────────────┬────────────┬───────┬────────────┐
│ id_cliente ┆ nombre    ┆ apellidos   ┆ sexo   ┆ … ┆ antiguedad ┆ nivel_clie ┆ socio ┆ tipo_clien │
│ ---        ┆ ---       ┆ ---         ┆ ---    ┆   ┆ ---        ┆ nte        ┆ ---   ┆ te         │
│ i64        ┆ str       ┆ str         ┆ str    ┆   ┆ i32        ┆ ---        ┆ bool  ┆ ---        │
│            ┆           ┆             ┆        ┆   ┆            ┆ str        ┆       ┆ str        │
╞════════════╪═══════════╪═════════════╪════════╪═══╪════════════╪════════════╪═══════╪════════════╡
│ 1          ┆ Álvaro    ┆ Castro      ┆ Mujer  ┆ … ┆ 3          ┆ Habitual   ┆ false ┆ Normal     │
│            ┆           ┆ Navarro     ┆        ┆   ┆            ┆            ┆       ┆            │
│ 2          ┆ Miguel    ┆ Martín      ┆ Mujer  ┆ … ┆ 4          ┆ Veterano   ┆ false ┆ Ocasional  │
│            ┆           ┆ Sánchez     ┆        ┆   ┆            ┆            ┆       ┆            │
│ 3          ┆ Elena     ┆ Romero      ┆ Mujer  ┆ … ┆ 3          ┆ Habitual   ┆ true  ┆ Normal     │
│            ┆           ┆ Ortega      ┆        ┆   ┆            ┆            ┆       ┆            │
│ 4          ┆ María     ┆ Romero      ┆ Hombre ┆ … ┆ 2          ┆ Habitual   ┆ true  ┆ Normal     │
│            ┆           ┆ Pérez       ┆        ┆   ┆            ┆            ┆       ┆            │
│ 5          ┆ Alejandro ┆ Jiménez     ┆ Mujer  ┆ … ┆ 4          ┆ Veterano   ┆ true  ┆ Frecuente  │
│            ┆           ┆ Castro      ┆        ┆   ┆            ┆            ┆       ┆            │
└────────────┴───────────┴─────────────┴────────┴───┴────────────┴────────────┴───────┴────────────┘

# Productos

# Ventas

**Ejercicio**

Hacer lo mismo para productos y ventas.